// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function ClearClickArea() {
  return window['go']['main']['App']['ClearClickArea']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DisableClickThrough() {
  return window['go']['main']['App']['DisableClickThrough']();
}

export function EnableClickThrough() {
  return window['go']['main']['App']['EnableClickThrough']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetSavedMonitorIndex() {
  return window['go']['main']['App']['GetSavedMonitorIndex']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetClickArea(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetClickArea'](arg1, arg2, arg3, arg4);
}

export function SetMonitor(arg1) {
  return window['go']['main']['App']['SetMonitor'](arg1);
}
