// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureScreen():Promise<string>;

export function CheckForUpdate(arg1:boolean):Promise<void>;

export function ClearClickArea():Promise<void>;

export function CloseApp():Promise<void>;

export function DisableClickThrough():Promise<void>;

export function EnableClickThrough():Promise<void>;

export function GetMonitors():Promise<Array<main.MonitorInfo>>;

export function GetSavedMonitorIndex():Promise<number>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallUpdate():Promise<void>;

export function SetClickArea(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetMonitor(arg1:number):Promise<void>;
